In [18]:
import pandas as pd
import numpy as np

df_vendas = pd.read_csv('train.csv', encoding="utf-8", sep=",", low_memory=False)
display(list(df_vendas.columns))
display(df_vendas.sample(50))
display(df_vendas.describe())
display(df_vendas.info())
display(df_vendas.isna().sum())
df_vendas[df_vendas["Postal Code"].isnull()]

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales']

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
1283,1284,CA-2018-122154,09/04/2018,11/04/2018,First Class,SA-20830,Sue Ann Reed,Consumer,United States,Jacksonville,Florida,32216.0,South,OFF-PA-10000994,Office Supplies,Paper,Xerox 1915,251.640
3693,3694,US-2016-131359,30/10/2016,02/11/2016,Second Class,FA-14230,Frank Atkinson,Corporate,United States,Denver,Colorado,80219.0,West,FUR-FU-10003026,Furniture,Furnishings,"Eldon Regeneration Recycled Desk Accessories, ...",15.488
1365,1366,US-2018-155425,10/11/2018,11/11/2018,First Class,AB-10600,Ann Blume,Corporate,United States,Tucson,Arizona,85705.0,West,TEC-AC-10001314,Technology,Accessories,Case Logic 2.4GHz Wireless Keyboard,239.952
5954,5955,CA-2015-155796,11/11/2015,15/11/2015,Second Class,TS-21430,Tom Stivers,Corporate,United States,Reading,Pennsylvania,19601.0,East,FUR-FU-10000409,Furniture,Furnishings,"GE 4 Foot Flourescent Tube, 40 Watt",23.968
4767,4768,CA-2016-123155,09/03/2016,12/03/2016,First Class,NS-18640,Noel Staavos,Corporate,United States,San Antonio,Texas,78207.0,Central,TEC-PH-10001809,Technology,Phones,Panasonic KX T7736-B Digital phone,359.880
1214,1215,US-2018-118087,09/09/2018,13/09/2018,Standard Class,SP-20620,Stefania Perrino,Corporate,United States,Philadelphia,Pennsylvania,19134.0,East,OFF-BI-10000069,Office Supplies,Binders,"GBC Prepunched Paper, 19-Hole, for Binding Sys...",4.503
5247,5248,US-2016-168914,21/05/2016,27/05/2016,Standard Class,JE-15745,Joel Eaton,Consumer,United States,Frankfort,Illinois,60423.0,Central,OFF-AP-10000358,Office Supplies,Appliances,Fellowes Basic Home/Office Series Surge Protec...,20.768
3323,3324,CA-2016-120810,23/07/2016,27/07/2016,Standard Class,TH-21550,Tracy Hopkins,Home Office,United States,New York City,New York,10009.0,East,FUR-FU-10002253,Furniture,Furnishings,"Howard Miller 13"" Diameter Pewter Finish Round...",128.820
740,741,CA-2015-112326,04/01/2015,08/01/2015,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540.0,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736
6635,6636,CA-2018-144498,06/05/2018,06/05/2018,Same Day,MB-18085,Mick Brown,Consumer,United States,Charlotte,North Carolina,28205.0,South,TEC-PH-10004977,Technology,Phones,GE 30524EE4,627.168
9652,9653,CA-2017-107104,26/11/2017,30/11/2017,Standard Class,MS-17365,Maribeth Schnelling,Consumer,United States,Los Angeles,California,90045.0,West,FUR-FU-10002937,Furniture,Furnishings,"GE 48"" Fluorescent Tube, Cool White Energy Sav...",595.380
9265,9266,US-2018-128118,24/11/2018,01/12/2018,Standard Class,MY-17380,Maribeth Yedwab,Corporate,United States,Memphis,Tennessee,38109.0,South,OFF-EN-10003448,Office Supplies,Envelopes,"Peel & Seel Recycled Catalog Envelopes, Brown",64.848
8038,8039,CA-2018-109393,30/06/2018,02/07/2018,Second Class,JC-15775,John Castell,Consumer,United States,Los Angeles,California,90032.0,West,FUR-BO-10003966,Furniture,Bookcases,"Sauder Facets Collection Library, Sky Alder Fi...",435.999
6017,6018,CA-2015-102652,06/04/2015,12/04/2015,Standard Class,AY-10555,Andy Yotov,Corporate,United States,Los Angeles,California,90049.0,West,OFF-PA-10003309,Office Supplies,Paper,Xerox 211,19.440
3467,3468,US-2016-147242,10/09/2016,14/09/2016,Standard Class,EH-13765,Edward Hooks,Corporate,United States,Revere,Massachusetts,2151.0,East,OFF-PA-10003039,Office Supplies,Paper,Xerox 1960,278.820
1343,1344,CA-2016-131758,28/05/2016,01/06/2016,Standard Class,KB-16315,Karl Braun,Consumer,United States,Freeport,New York,11520.0,East,OFF-AR-10000411,Office Supplies,Art,Boston 16701 Slimline Battery Pencil Sharpener,47.820
3082,3083,US-2018-132297,27/05/2018,02/06/2018,Standard Class,DW-13480,Dianna Wilson,Home Office,United States,Louisville,Kentucky,40214.0,South,TEC-PH-10002834,Technology,Phones,Google Nexus 5,539.970
1794,1795,CA-2017-140774,05/09/2017,10/09/2017,Standard Class,BE-11455,Brad Eason,Home Office,United States,Olathe,Kansas,66062.0,Central,OFF-AR-10004022,Office Supplies,Art,Panasonic KP-380BK Classic Electric Pencil Sha...,107.940
4533,4534,CA-2015-140403,10/10/2015,10/10/2015,Same Day,TN-21040,Tanja Norvell,Home Office,United States,Manteca,California,95336.0,West,OFF-EN-10001219,Office Supplies,Envelopes,"#10- 4 1/8"" x 9 1/2"" Security-Tint Envelopes",15.280
7714,7715,CA-2015-150203,05/12/2015,07/12/2015,First Class,JB-15925,Joni Blumstein,Consumer,United States,Los Angeles,California,90032.0,West,OFF-AP-10001469,Office Supplies,Appliances,Fellowes 8 Outlet Superior Workstation Surge P...,250.260
6064,6065,CA-2016-111780,25/12/2016,30/12/2016,Second Class,RA-19285,Ralph Arnett,Consumer,United States,San Diego,California,92037.0,West,OFF-PA-10001667,Office Supplies,Paper,Great White Multi-Use Recycled Paper (20Lb. an...,17.940
950,951,US-2018-110576,28/11/2018,02/12/2018,Standard Class,RB-19795,Ross Baird,Home Office,United States,Philadelphia,Pennsylvania,19120.0,East,OFF-PA-10000788,Office Supplies,Paper,Xerox 210,15.552
2423,2424,US-2018-147669,25/12/2018,30/12/2018,Standard Class,SV-20935,Susan Vittorini,Consumer,United States,Fairfield,Ohio,45014.0,East,TEC-AC-10002473,Technology,Accessories,Maxell 4.7GB DVD-R,158.928
4182,4183,US-2018-136868,06/10/2018,12/10/2018,Standard Class,CR-12820,Cyra Reiten,Home Office,United States,New York City,New York,10035.0,East,OFF-PA-10002377,Office Supplies,Paper,Adams Telephone Message Book W/Dividers/Space ...,17.040
3243,3244,CA-2018-113355,01/12/2018,05/12/2018,Standard Class,SJ-20215,Sarah Jordon,Consumer,United States,Grand Prairie,Texas,75051.0,Central,TEC-PH-10004912,Technology,Phones,Cisco SPA112 2 Port Phone Adapter,219.800
5814,5815,US-2016-106495,15/06/2016,17/06/2016,First Class,AC-10450,Amy Cox,Consumer,United States,Tampa,Florida,33614.0,South,TEC-AC-10002718,Technology,Accessories,Belkin Standard 104 key USB Keyboard,11.672
6070,6071,CA-2018-167542,13/08/2018,20/08/2018,Standard Class,KD-16495,Keith Dawkins,Corporate,United States,Philadelphia,Pennsylvania,19120.0,East,OFF-LA-10004093,Office Supplies,Labels,Avery 486,17.544
1860,1861,US-2018-121251,26/03/2018,27/03/2018,First Class,GM-14440,Gary McGarr,Consumer,United States,New York City,New York,10009.0,East,FUR-BO-10001918,Furniture,Bookcases,"Sauder Forest Hills Library with Doors, Woodla...",257.568
4720,4721,CA-2016-142601,18/04/2016,20/04/2016,Second Class,DE-13255,Deanra Eno,Home Office,United States,Los Angeles,California,90004.0,West,OFF-PA-10000483,Office Supplies,Paper,Xerox 19,61.960
6805,6806,CA-2015-125682,22/11/2015,25/11/2015,First Class,RB-19645,Robert Barroso,Corporate,United States,Atlanta,Georgia,30318.0,South,OFF-PA-10001752,Office Supplies,Paper,Hammermill CopyPlus Copy Paper (20Lb. and 84 B...,9.960
381,382,CA-2017-134775,28/10/2017,29/10/2017,First Class,AS-10285,Alejandro Savely,Corporate,United States,San Francisco,California,94109.0,West,OFF-PA-10004734,Office Supplies,Paper,Southworth Structures Collection,50.960
9679,9680,CA-2016-130113,27/12/2016,31/12/2016,Standard Class,AH-10030,Aaron Hawkins,Corporate,United States,San Francisco,California,94122.0,West,OFF-ST-10000046,Office Supplies,Storage,Fellowes Super Stor/Drawer Files,323.100
1269,1270,CA-2018-100426,04/06/2018,08/06/2018,Standard Class,DC-12850,Dan Campbell,Consumer,United States,Florence,Alabama,35630.0,South,OFF-PA-10002870,Office Supplies,Paper,"Ampad Phone Message Book, Recycled, 400 Messag...",12.480
6983,6984,CA-2017-116526,01/09/2017,05/09/2017,Standard Class,JA-15970,Joseph Airdo,Consumer,United States,Detroit,Michigan,48227.0,Central,TEC-PH-10002365,Technology,Phones,Belkin Grip Candy Sheer Case / Cover for iPhon...,8.780
978,979,CA-2017-145499,30/05/2017,31/05/2017,First Class,RW-19690,Robert Waldorf,Consumer,United States,Wilmington,North Carolina,28403.0,South,OFF-BI-10000848,Office Supplies,Binders,Angle-D Ring Binders,3.282
5509,5510,US-2018-152569,15/05/2018,20/05/2018,Standard Class,JD-16015,Joy Daniels,Consumer,United States,Chicago,Illinois,60653.0,Central,OFF-PA-10001736,Office Supplies,Paper,Xerox 1880,56.704
4661,4662,CA-2016-112130,03/05/2016,07/05/2016,Standard Class,SV-20785,Stewart Visinsky,Consumer,United States,Philadelphia,Pennsylvania,19140.0,East,FUR-CH-10002965,Furniture,Chairs,Global Leather Highback Executive Chair with P...,844.116
4011,4012,CA-2018-100811,21/11/2018,24/11/2018,First Class,CC-12475,Cindy Chapman,Consumer,United States,Philadelphia,Pennsylvania,19143.0,East,OFF-ST-10002444,Office Supplies,Storage,Recycled Eldon Regeneration Jumbo File,39.296
1143,1144,CA-2015-146969,29/09/2015,03/10/2015,Standard Class,AP-10915,Arthur Prichep,Consumer,United States,Los Angeles,California,90045.0,West,OFF-PA-10002105,Office Supplies,Paper,Xerox 223,6.480
8864,8865,CA-2016-125934,11/09/2016,18/09/2016,Standard Class,SN-20560,Skye Norling,Home Office,United States,Paterson,New Jersey,7501.0,East,OFF-PA-10000556,Office Supplies,Paper,Xerox 208,38.880
6019,6020,CA-2015-152422,05/10/2015,10/10/2015,Second Class,BD-11635,Brian Derr,Consumer,United States,Columbus,Ohio,43229.0,East,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,91.920
6465,6466,CA-2016-114503,13/11/2016,17/11/2016,Standard Class,AA-10375,Allen Armold,Consumer,United States,Lebanon,Tennessee,37087.0,South,OFF-ST-10003572,Office Supplies,Storage,Portfile Personal File Boxes,84.960
6549,6550,US-2016-164966,30/07/2016,01/08/2016,First Class,GH-14410,Gary Hansen,Home Office,United States,Lakeville,Minnesota,55044.0,Central,FUR-CH-10002304,Furniture,Chairs,"Global Stack Chair without Arms, Black",155.880
2458,2459,CA-2018-140949,17/03/2018,22/03/2018,Second Class,DB-13405,Denny Blanton,Consumer,United States,New York City,New York,10011.0,East,OFF-ST-10003455,Office Supplies,Storage,"Tenex File Box, Personal Filing Tote with Lid,...",46.530
9626,9627,CA-2018-103520,23/09/2018,25/09/2018,First Class,MH-17785,Maya Herman,Corporate,United States,Lubbock,Texas,79424.0,Central,OFF-PA-10001846,Office Supplies,Paper,Xerox 1899,9.248
1864,1865,US-2017-100839,13/10/2017,17/10/2017,Standard Class,NC-18625,Noah Childs,Corporate,United States,Aurora,Colorado,80013.0,West,FUR-FU-10001617,Furniture,Furnishings,"Executive Impressions 8-1/2"" Career Panel/Part...",24.960
3537,3538,CA-2015-158771,09/05/2015,09/05/2015,Same Day,SB-20290,Sean Braxton,Corporate,United States,Henderson,Kentucky,42420.0,South,OFF-ST-10000107,Office Supplies,Storage,Fellowes Super Stor/Drawer,83.250
8790,8791,CA-2016-169572,06/09/2016,12/09/2016,Standard Class,AG-10525,Andy Gerbode,Corporate,United States,Richmond,Virginia,23223.0,South,OFF-BI-10002799,Office Supplies,Binders,"SlimView Poly Binder, 3/8""",46.620
7137,7138,CA-2016-163965,20/11/2016,27/11/2016,Standard Class,SS-20875,Sung Shariari,Consumer,United States,Miami,Florida,33180.0,South,OFF-ST-10000918,Office Supplies,Storage,Crate-A-Files,17.440
4525,4526,US-2018-105046,17/07/2018,23/07/2018,Standard Class,BE-11335,Bill Eplett,Home Office,United States,Rome,New York,13440.0,East,TEC-PH-10004536,Technology,Phones,Avaya 5420 Digital phone,269.980

            Row ID   Postal Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   str
 2   Order Date     9800 non-null   str
 3   Ship Date      9800 non-null   str
 4   Ship Mode      9800 non-null   str
 5   Customer ID    9800 non-null   str
 6   Customer Name  9800 non-null   str
 7   Segment        9800 non-null   str
 8   Country        9800 non-null   str
 9   City           9800 non-null   str
 10  State          9800 non-null   str
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   str
 13  Product ID     9800 non-null   str
 14  Category       9800 non-null   str
 15  Sub-Category   9800 non-null   str
 16  Product Name   9800 non-null   str
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), str(15)
memory usage: 1.3 MB

None

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
2234,2235,CA-2018-104066,05/12/2018,10/12/2018,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,Vermont,NaN,East,TEC-AC-10001013,Technology,Accessories,Logitech ClearChat Comfort/USB Headset H390,205.03
5274,5275,CA-2016-162887,07/11/2016,09/11/2016,Second Class,SV-20785,Stewart Visinsky,Consumer,United States,Burlington,Vermont,NaN,East,FUR-CH-10000595,Furniture,Chairs,Safco Contoured Stacking Chairs,715.20
8798,8799,US-2017-150140,06/04/2017,10/04/2017,Standard Class,VM-21685,Valerie Mitchum,Home Office,United States,Burlington,Vermont,NaN,East,TEC-PH-10002555,Technology,Phones,Nortel Meridian M5316 Digital phone,1294.75
9146,9147,US-2017-165505,23/01/2017,27/01/2017,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,NaN,East,TEC-AC-10002926,Technology,Accessories,Logitech Wireless Marathon Mouse M705,99.98
9147,9148,US-2017-165505,23/01/2017,27/01/2017,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,NaN,East,OFF-AR-10003477,Office Supplies,Art,4009 Highlighters,8.04
9148,9149,US-2017-165505,23/01/2017,27/01/2017,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,NaN,East,OFF-ST-10001526,Office Supplies,Storage,Iceberg Mobile Mega Data/Printer Cart,1564.29
9386,9387,US-2018-127292,19/01/2018,23/01/2018,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-PA-10000157,Office Supplies,Paper,Xerox 191,79.92
9387,9388,US-2018-127292,19/01/2018,23/01/2018,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-PA-10001970,Office Supplies,Paper,Xerox 1881,12.28
9388,9389,US-2018-127292,19/01/2018,23/01/2018,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-AP-10000828,Office Supplies,Appliances,Avanti 4.4 Cu. Ft. Refrigerator,542.94
9389,9390,US-2018-127292,19/01/2018,23/01/2018,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-EN-10001509,Office Supplies,Envelopes,Poly String Tie Envelopes,2.04
9741,9742,CA-2016-117086,08/11/2016,12/11/2016,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,Vermont,NaN,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",4404.90